dist: xenial
addons:
  chrome: stable
language: node_js
cache: npm
node_js:
  - '12'
script:
  - npm run lint
  - npm run build
  - npm run test:prod
  - npm run integration-test:prod
branches:
  only:
    - master
