language: node_js
node_js:
  - '12'
  - '10'
  - '8'
script:
  - npm run test:prod
  - npm run build
  # TODO Add integration test here
jobs:
  include:
    - stage: deploy
      script: skip
      node_js: '12'
      deploy: &github
        provider: releases
        on:
          tags: true
        skip_cleanup: true
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/ # versions like v1.0.0
