language: node_js
node_js:
  - '12'
  - '10'
  - '8'
jobs:
  include:
    - stage: test
      script: npm run test:prod
    - stage: build
      script: npm run build
after_success:
  - echo success
branches:
  except:
    - /^v\d+\.\d+\.\d+$/ # versions like v1.0.0
